default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dev_green-api

production:
  <<: *default
  database: prod_green-api  

test:
  <<: *default
  database: test_green-api  